//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSolutionBanking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int sn { get; set; }
        public string CustomerNo { get; set; }
        public string AccountNumber { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Othername { get; set; }
        public string Phone { get; set; }
        public string AccountType { get; set; }
        public decimal Balance { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime DateRegister { get; set; }
    }
}
